### ISSUE TITLE
when i use arrow keys this shown 

### ISSUE THREAD

**Issue by SeanBeansShako** [elmoiv/pubg_no_recoil#2]
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\pubg_no_recoil-master\pubg_recoil.py", line 32, in no_recoil
    save_cfg()
  File "D:\pubg_no_recoil-master\pubg_recoil.py", line 11, in save_cfg
    with open('pubg_recoil.cfg', 'w') as cfg:
PermissionError: [Errno 13] Permission denied: 'pubg_recoil.cfg'

**Comment by elmoiv** [comment]
Run as Adminstrator.
If faced problems with the script try the release from here:
https://mega.nz/file/0I03EIqC#eWhuFhOH59HE4je7emqFXoaCSknJJM3xa_WEktK9rSE

*ALWAYS RUN AS ADMIN* to give the program permission to write.
